(() => {
  'use strict';
  const frame=document.getElementById('celeste-frame'),veil=document.getElementById('privacy-veil'),showBtn=document.getElementById('privacy-show'),quickHide=document.getElementById('quick-hide');
  let app=null,enhanced=false,audioCtx=null;
  function showPrivacy(){veil.classList.remove('hidden');quickHide.style.display='none';try{app?.stopTTS?.();if(app?.autoMode)app.toggleAuto?.();}catch(_){}}
  function reveal(){veil.classList.add('hidden');quickHide.style.display='block';try{app?.unlockAppAudio?.('privacy-reveal');}catch(_){}}
  showBtn.addEventListener('click',reveal);quickHide.addEventListener('click',showPrivacy);document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')showPrivacy();});window.addEventListener('pagehide',showPrivacy);
  function css(doc){const s=doc.createElement('style');s.textContent=`.enhanced-card{background:rgba(255,255,255,.72);border:1px solid rgba(255,255,255,.9);border-radius:22px;padding:18px;margin:0 0 14px;box-shadow:0 8px 28px rgba(180,130,180,.10)}.enh-title{font-family:'Playfair Display',serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:12px;display:flex;align-items:center;gap:8px}.feedback-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.feedback-option{background:rgba(255,255,255,.78);border:1px solid rgba(255,255,255,.9);border-radius:14px;padding:10px 12px}.feedback-option label{display:flex;align-items:center;justify-content:space-between;gap:10px;font-size:12px;font-weight:800;color:var(--text)}.feedback-option input[type=checkbox]{width:20px;height:20px;accent-color:var(--pink)}.feedback-option select,.feedback-option input[type=range]{width:100%;margin-top:8px}.feedback-hint{font-size:10px;color:var(--text-soft);font-weight:700;margin-top:9px;line-height:1.4}.heatmap-wrap{overflow-x:auto;padding-bottom:4px}.heatmap{display:grid;grid-template-rows:repeat(7,14px);grid-auto-flow:column;grid-auto-columns:14px;gap:4px;width:max-content}.heat-cell{width:14px;height:14px;border-radius:4px;background:rgba(160,150,175,.12);border:1px solid rgba(255,255,255,.75)}.heat-cell.l1{background:rgba(255,133,161,.24)}.heat-cell.l2{background:rgba(255,133,161,.44)}.heat-cell.l3{background:rgba(201,127,255,.60)}.heat-cell.l4{background:rgba(143,187,246,.82)}.heat-legend{display:flex;align-items:center;gap:5px;justify-content:flex-end;margin-top:8px;font-size:9px;color:var(--text-soft);font-weight:800}.heat-legend span{width:11px;height:11px;border-radius:3px;display:inline-block}.records-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.record-box{background:rgba(255,255,255,.78);border:1px solid rgba(255,255,255,.9);border-radius:15px;padding:11px 8px;text-align:center}.record-val{font-family:'Playfair Display',serif;font-size:20px;font-weight:900;color:var(--text)}.record-lbl{font-size:9px;text-transform:uppercase;letter-spacing:.8px;color:var(--text-soft);font-weight:900;margin-top:3px}@media(max-width:520px){.feedback-grid{grid-template-columns:1fr}.records-grid{grid-template-columns:repeat(2,1fr)}}`;doc.head.appendChild(s);}
  function settings(){return{sound:app.localStorage.getItem('celeste_rep_sound')==='1',haptic:app.localStorage.getItem('celeste_rep_haptic')==='1',every:Math.max(1,parseInt(app.localStorage.getItem('celeste_rep_every')||'1',10)||1),tone:app.localStorage.getItem('celeste_rep_tone')||'soft',volume:Math.min(1,Math.max(.05,parseFloat(app.localStorage.getItem('celeste_rep_volume')||'.35')||.35))};}
  function save(k,v){app.localStorage.setItem(k,String(v));}
  function sound(tone,volume){const AC=app.AudioContext||app.webkitAudioContext;if(!AC)return;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain(),tones={soft:{f:560,type:'sine',d:.045},crystal:{f:920,type:'sine',d:.07},pop:{f:330,type:'triangle',d:.035}},c=tones[tone]||tones.soft;o.type=c.type;o.frequency.setValueAtTime(c.f,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.0001,volume*.18),now+.005);g.gain.exponentialRampToValueAtTime(.0001,now+c.d);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+c.d+.01);}
  function feedback(){const s=settings(),count=Number(app.sessionCount||0);if(!count||count%s.every!==0)return;if(s.haptic&&app.navigator.vibrate)app.navigator.vibrate(18);if(s.sound)sound(s.tone,s.volume);}
  function addFeedback(doc){const timer=doc.querySelector('.affirm-timer-bar');if(!timer||doc.getElementById('rep-feedback-card'))return;const s=settings(),card=doc.createElement('div');card.className='enhanced-card';card.id='rep-feedback-card';card.innerHTML=`<div class="enh-title">🔉 Feedback por repetición</div><div class="feedback-grid"><div class="feedback-option"><label>Sonido <input id="rep-sound" type="checkbox" ${s.sound?'checked':''}></label><select id="rep-tone"><option value="soft">Suave</option><option value="crystal">Cristal</option><option value="pop">Pop</option></select></div><div class="feedback-option"><label>Vibración <input id="rep-haptic" type="checkbox" ${s.haptic?'checked':''}></label><select id="rep-every"><option value="1">Cada repetición</option><option value="5">Cada 5</option><option value="10">Cada 10</option><option value="25">Cada 25</option></select></div></div><div class="feedback-option" style="margin-top:10px"><label>Volumen del sonido <span id="rep-volume-label">${Math.round(s.volume*100)}%</span></label><input id="rep-volume" type="range" min="0.05" max="1" step="0.05" value="${s.volume}"></div><div class="feedback-hint">Podés afirmar sin mirar la pantalla: el sonido o la vibración te confirman cada repetición (o cada X repeticiones).</div>`;timer.parentNode.insertBefore(card,timer);doc.getElementById('rep-tone').value=s.tone;doc.getElementById('rep-every').value=String(s.every);doc.getElementById('rep-sound').addEventListener('change',e=>save('celeste_rep_sound',e.target.checked?'1':'0'));doc.getElementById('rep-haptic').addEventListener('change',e=>save('celeste_rep_haptic',e.target.checked?'1':'0'));doc.getElementById('rep-tone').addEventListener('change',e=>{save('celeste_rep_tone',e.target.value);sound(e.target.value,settings().volume)});doc.getElementById('rep-every').addEventListener('change',e=>save('celeste_rep_every',e.target.value));doc.getElementById('rep-volume').addEventListener('input',e=>{save('celeste_rep_volume',e.target.value);doc.getElementById('rep-volume-label').textContent=Math.round(Number(e.target.value)*100)+'%'});}
  function counts(){const out={};for(let i=0;i<app.localStorage.length;i++){const k=app.localStorage.key(i),m=k&&k.match(/^celeste_daily_.+_(\d{4}-\d{2}-\d{2})$/);if(m)out[m[1]]=(out[m[1]]||0)+(parseInt(app.localStorage.getItem(k),10)||0);}if(!Object.keys(out).length&&app.getHistory)app.getHistory().forEach(e=>{const d=new Date(e.ts);if(!Number.isNaN(d.getTime())){const k=app.dateKey(d);out[k]=(out[k]||0)+1}});return out;}
  function streak(c){const days=Object.keys(c).filter(k=>c[k]>0).sort();if(!days.length)return 0;let best=1,cur=1;for(let i=1;i<days.length;i++){const p=new Date(days[i-1]+'T12:00:00'),n=new Date(p);n.setDate(n.getDate()+1);if(app.dateKey(n)===days[i]){cur++;best=Math.max(best,cur)}else cur=1;}return best;}
  function week(c){const sums={};Object.entries(c).forEach(([day,n])=>{const d=new Date(day+'T12:00:00'),dow=(d.getDay()+6)%7;d.setDate(d.getDate()-dow);const w=app.dateKey(d);sums[w]=(sums[w]||0)+n});return Math.max(0,...Object.values(sums));}
  function render(){if(!app?.document)return;const c=counts(),doc=app.document,r=doc.getElementById('enh-records'),map=doc.getElementById('enh-heatmap');if(r){const vals=Object.values(c),best=vals.length?Math.max(...vals):0,total=vals.reduce((a,b)=>a+b,0);r.innerHTML=`<div class="record-box"><div class="record-val">${best.toLocaleString()}</div><div class="record-lbl">Mejor día</div></div><div class="record-box"><div class="record-val">${streak(c)}</div><div class="record-lbl">Racha récord</div></div><div class="record-box"><div class="record-val">${week(c).toLocaleString()}</div><div class="record-lbl">Mejor semana</div></div><div class="record-box"><div class="record-val">${total.toLocaleString()}</div><div class="record-lbl">Histórico diario</div></div>`;}if(map){map.innerHTML='';const end=new Date();end.setHours(12,0,0,0);const start=new Date(end);start.setDate(start.getDate()-90);start.setDate(start.getDate()-start.getDay());const vals=Object.values(c).filter(n=>n>0).sort((a,b)=>a-b),max=vals.length?vals[vals.length-1]:1;for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const k=app.dateKey(d),n=c[k]||0,l=n?Math.min(4,Math.max(1,Math.ceil(n/max*4))):0,cell=doc.createElement('div');cell.className='heat-cell'+(l?' l'+l:'');cell.title=`${d.toLocaleDateString('es-AR')}: ${n} repeticiones`;map.appendChild(cell);}}}
  function addHistory(doc){const card=doc.querySelector('#tab-historial .card');if(!card||doc.getElementById('enh-history-visual'))return;const box=doc.createElement('div');box.id='enh-history-visual';box.innerHTML=`<div class="enhanced-card"><div class="enh-title">🏆 Récords</div><div class="records-grid" id="enh-records"></div></div><div class="enhanced-card"><div class="enh-title">🗓 Últimos 90 días</div><div class="heatmap-wrap"><div class="heatmap" id="enh-heatmap"></div></div><div class="heat-legend">menos <span style="background:rgba(255,133,161,.24)"></span><span style="background:rgba(255,133,161,.44)"></span><span style="background:rgba(201,127,255,.60)"></span><span style="background:rgba(143,187,246,.82)"></span> más</div></div>`;const title=card.querySelector('.section-title');title?title.insertAdjacentElement('afterend',box):card.prepend(box);render();}
  function patch(){if(!app.nextAffirmation||app.__celesteEnhancedPatched)return;const next=app.nextAffirmation;app.nextAffirmation=function(...a){const before=Number(app.sessionCount||0),res=next.apply(this,a);if(Number(app.sessionCount||0)>before)feedback();return res};const sw=app.switchTab;if(sw)app.switchTab=function(name,btn){const res=sw.call(this,name,btn);if(name==='historial')setTimeout(render,0);return res};app.__celesteEnhancedPatched=true;}
  function unlock(){const doc=app.document,lock=doc.getElementById('lock-screen'),main=doc.getElementById('main-app');if(lock)lock.style.display='none';if(main){main.style.display='flex';main.style.flexDirection='column';main.style.alignItems='center';main.style.width='100%';}doc.querySelector('.lock-exit-btn')?.remove();if(!app.__celesteInitFromWrapper){app.__celesteInitFromWrapper=true;try{app.initApp?.();}catch(e){console.error(e)}}}
  function enhance(){if(enhanced)return;app=frame.contentWindow;if(!app||!app.document)return;enhanced=true;unlock();css(app.document);addFeedback(app.document);addHistory(app.document);patch();render();}
  frame.addEventListener('load',enhance);setTimeout(()=>{if(!enhanced&&frame.contentDocument?.readyState==='complete')enhance()},800);
})();