// Rutina — Service Worker
const CACHE_NAME = 'celeste-v13';
const ASSETS = ['./index.html','./legacy.html','./enhancements.js','./intensity-safe.js','./theme-safe.js','./manifest.json','./icon-192.png','./icon-512.png'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(ASSETS).catch(err=>console.warn('Cache:',err))));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim();});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;const networkFirst=url.pathname.endsWith('index.html')||url.pathname.endsWith('/')||url.pathname.endsWith('legacy.html')||url.pathname.endsWith('.js')||url.pathname.endsWith('manifest.json');if(networkFirst){event.respondWith(fetch(event.request).then(response=>{const clone=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,clone));return response;}).catch(()=>caches.match(event.request)));}else{event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response&&response.ok){const clone=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,clone));}return response;})));}});
self.addEventListener('message',event=>{if(event.data?.type==='SCHEDULE_REMINDERS')self.reminders=event.data.reminders||[];if(event.data?.type==='GET_STATUS')event.source.postMessage({type:'SW_READY'});});
self.addEventListener('periodicsync',event=>{if(event.tag==='check-reminders')event.waitUntil(checkAndNotify());});
self.addEventListener('push',event=>{const data=event.data?event.data.json():{title:'Rutina',body:'Recordatorio de tu rutina'};event.waitUntil(self.registration.showNotification(data.title||'Rutina',{body:data.body||'Recordatorio de tu rutina',icon:'./icon-192.png',badge:'./icon-192.png',vibrate:[200,100,200],tag:'rutina-reminder',renotify:true,data:{url:self.location.origin+self.location.pathname}}));});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){if(c.url.includes('index.html')||c.url.endsWith('/'))return c.focus();}return clients.openWindow(event.notification.data?.url||'./index.html');}));});
async function checkAndNotify(){const reminders=self.reminders||[],now=new Date(),hhmm=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0'),dow=now.getDay();for(const r of reminders){if(r.paused||!r.days.includes(dow)||r.time!==hhmm)continue;await self.registration.showNotification('Rutina',{body:r.msg,icon:'./icon-192.png',badge:'./icon-192.png',vibrate:[200,100,200],tag:'rutina-'+r.id,renotify:true,data:{url:self.location.href}});}}
