(() => {
'use strict';
const frame=document.getElementById('celeste-frame'),KEY='celeste_theme_mode';let installedDoc=null;
const getMode=()=>{try{return localStorage.getItem(KEY)||'light'}catch(_){return'light'}};
function outer(m){const d=m!=='light',o=m==='oled';document.body.style.background=o?'#000':d?'#111014':'#f7eef7';frame.style.background=o?'#000':d?'#111014':'#fff';const x=document.querySelector('meta[name="theme-color"]');if(x)x.content=o?'#000':d?'#111014':'#ff85a1';}
function style(doc){let s=doc.getElementById('celeste-theme-safe-style');if(s)s.remove();s=doc.createElement('style');s.id='celeste-theme-safe-style';s.textContent=`
#celeste-theme-control{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;margin:0 auto 14px;width:min(100%,var(--panel-max-width))}#celeste-theme-control button{border-radius:13px;padding:8px 11px;font-family:'Nunito',sans-serif;font-weight:800;font-size:11px;cursor:pointer}
body.celeste-dark,body.celeste-oled{color-scheme:dark}body.celeste-dark{background:#111014!important;--glass:#211f25;--glass-strong:#29262e;--text:#f7f2f8;--text-soft:#bbb4c0;--shadow:0 8px 28px #0006}body.celeste-oled{background:#000!important;--glass:#070707;--glass-strong:#0d0d0d;--text:#faf7fb;--text-soft:#b8b2bc;--shadow:none}
body.celeste-oled #main-app .card{background:#030303!important;border-color:#242424!important;box-shadow:none!important;backdrop-filter:none!important}
body.celeste-oled #main-app :is(.affirm-timer-bar,.affirm-timer-top,.affirm-timer-custom,.timer-sound-custom,.timer-volume-row,.tts-bar,.meta-total-row,.speed-row,.stat-box,.stats-row,.feedback-row,.feedback-slider,.record-box){background:#080808!important;border-color:#2b2b2b!important;color:#f7f7f8!important;box-shadow:none!important;backdrop-filter:none!important}
body.celeste-oled #main-app :is(input:not([type=range]),select,textarea){background:#050505!important;color:#fafafa!important;border-color:#333!important;box-shadow:none!important}
body.celeste-oled #main-app :is(.btn-sec,.atbtn-reset,.atpreset:not(.active),.feedback-test button,.btn-add:not(.pink),.tab-btn:not(.active),.pill:not(.active),#celeste-theme-control button:not(.active)){background:#0b0b0b!important;color:#f0edf2!important;border-color:#333!important;box-shadow:none!important}
body.celeste-oled #main-app .timer-clock{background:conic-gradient(from -90deg,var(--pink) 0%,#c97fff var(--timer-progress),#222 var(--timer-progress),#222 100%)!important;box-shadow:none!important}body.celeste-oled #main-app .timer-clock::before{background:#050505!important;box-shadow:none!important}
body.celeste-oled #main-app .affirm-timer-title,body.celeste-oled #main-app .stat-lbl{color:#bdb6c0!important}body.celeste-oled #main-app .streak-banner{background:linear-gradient(135deg,#170a10,#110817)!important;border-color:#3b1e31!important}body.celeste-oled #main-app .prog-wrap{background:#232323!important}
body.celeste-oled #main-app input[type=range]{background:transparent!important;border:0!important}body.celeste-oled #main-app option{background:#050505;color:#fff}
body.celeste-dark #main-app :is(.card,.affirm-timer-bar,.tts-bar,.meta-total-row,.speed-row,.stat-box,.feedback-row,.feedback-slider){background:#211f25!important;border-color:#443e49!important;color:#f7f2f8!important}
body.celeste-dark #main-app :is(input:not([type=range]),select,textarea,.btn-sec,.atbtn-reset,.atpreset:not(.active),.pill:not(.active)){background:#2b2830!important;color:#f8f4f9!important;border-color:#4b4551!important}
body.celeste-dark #main-app .timer-clock::before{background:#1b191e!important}
body.celeste-dark #celeste-theme-control button,body.celeste-oled #celeste-theme-control button{background:#0b0b0b;color:#eee8f0;border:1px solid #303030}body.celeste-dark #celeste-theme-control button.active,body.celeste-oled #celeste-theme-control button.active{background:linear-gradient(135deg,#ff6e99,#b968ff)!important;color:#fff!important;border-color:transparent!important}
`;doc.head.appendChild(s)}
function forceOLED(doc,m){if(m!=='oled')return;const dark='#080808',border='#2b2b2b',text='#f7f7f8';const q=s=>doc.querySelectorAll(s);q('.affirm-timer-bar,.affirm-timer-top,.affirm-timer-custom,.timer-sound-custom,.timer-volume-row,.tts-bar,.meta-total-row,.speed-row,.stat-box,.feedback-row,.feedback-slider').forEach(el=>{el.style.setProperty('background',dark,'important');el.style.setProperty('border-color',border,'important');el.style.setProperty('color',text,'important');el.style.setProperty('box-shadow','none','important')});q('.affirm-timer-bar input:not([type=range]),.affirm-timer-bar select,.tts-bar select,.meta-total-row input').forEach(el=>{el.style.setProperty('background','#050505','important');el.style.setProperty('color','#fff','important');el.style.setProperty('border-color','#333','important')});q('.affirm-timer-bar .atbtn-reset,.affirm-timer-bar .atpreset:not(.active),.feedback-test button,.btn-sec,.btn-add:not(.pink)').forEach(el=>{el.style.setProperty('background','#0b0b0b','important');el.style.setProperty('color','#f3eef5','important');el.style.setProperty('border-color','#333','important')});const clock=doc.querySelector('.timer-clock');if(clock){clock.style.setProperty('box-shadow','none','important')}requestAnimationFrame(()=>{q('.affirm-timer-bar,.tts-bar,.meta-total-row,.speed-row,.stat-box').forEach(el=>{const c=getComputedStyle(el).backgroundColor.match(/\d+/g);if(c&&+c[0]>80&&+c[1]>80&&+c[2]>80)el.style.setProperty('background','#080808','important')})})}
function control(doc){if(doc.getElementById('celeste-theme-control'))return;const h=doc.querySelector('.app-header');if(!h)return;const b=doc.createElement('div');b.id='celeste-theme-control';b.innerHTML='<button data-theme="light">☀️ Claro</button><button data-theme="dark">🌙 Oscuro</button><button data-theme="oled">⚫ Ahorro OLED</button>';h.insertAdjacentElement('afterend',b);b.onclick=e=>{const x=e.target.closest('[data-theme]');if(x)setMode(x.dataset.theme)}}
function inner(doc,m){style(doc);control(doc);installedDoc=doc;doc.body.classList.toggle('celeste-dark',m==='dark');doc.body.classList.toggle('celeste-oled',m==='oled');doc.querySelectorAll('#celeste-theme-control button').forEach(b=>b.classList.toggle('active',b.dataset.theme===m));forceOLED(doc,m)}
function setMode(m){try{localStorage.setItem(KEY,m)}catch(_){}outer(m);if(frame.contentDocument)inner(frame.contentDocument,m)}
function install(){const d=frame.contentDocument;if(d&&d.body)inner(d,getMode())}
outer(getMode());frame.addEventListener('load',()=>setTimeout(install,150));let n=0,t=setInterval(()=>{install();if((installedDoc&&frame.contentDocument===installedDoc)||++n>80)clearInterval(t)},100);
})();