(() => {
'use strict';const frame=document.getElementById('celeste-frame'),KEY='celeste_theme_mode';let installedDoc=null;const getMode=()=>{try{return localStorage.getItem(KEY)||'light'}catch(_){return'light'}};
function outer(m){const d=m!=='light',o=m==='oled';document.body.style.background=o?'#000':d?'#111014':'#f7eef7';frame.style.background=o?'#000':d?'#111014':'#fff';const x=document.querySelector('meta[name="theme-color"]');if(x)x.content=o?'#000':d?'#111014':'#ff85a1';}
function style(doc){let s=doc.getElementById('celeste-theme-safe-style');if(s)s.remove();s=doc.createElement('style');s.id='celeste-theme-safe-style';s.textContent=`
#celeste-theme-control{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;margin:0 auto 14px;width:min(100%,var(--panel-max-width))}#celeste-theme-control button{border:1px solid rgba(255,133,161,.18);border-radius:13px;padding:8px 11px;font-family:'Nunito',sans-serif;font-weight:800;font-size:11px;cursor:pointer}
body.celeste-dark,body.celeste-oled{color-scheme:dark}body.celeste-dark{background:#111014!important;--glass:#211f25;--glass-strong:#29262e;--text:#f7f2f8;--text-soft:#bbb4c0;--shadow:0 8px 28px #0006}body.celeste-oled{background:#000!important;--glass:#070707;--glass-strong:#0d0d0d;--text:#faf7fb;--text-soft:#b8b2bc;--shadow:none}
body.celeste-dark :is(.card,.tab-bar,.celeste-addon-section,.affirm-timer-bar,.tts-bar,.meta-total-row,.stat-box,.speed-row,.affirm-timer-custom,.timer-volume-row,.robot-bar,.daily-progress,.habit-card,.task-card,.reminder-card,.evidence-card,.energy-card,.planner-card){background:#211f25!important;border-color:#443e49!important}
body.celeste-oled :is(.card,.tab-bar,.celeste-addon-section,.affirm-timer-bar,.tts-bar,.meta-total-row,.stat-box,.speed-row,.affirm-timer-custom,.timer-volume-row,.robot-bar,.daily-progress,.habit-card,.task-card,.reminder-card,.evidence-card,.energy-card,.planner-card){background:#050505!important;border-color:#292929!important;box-shadow:none!important;backdrop-filter:none!important}
body.celeste-dark :is(.affirmation-display,.feedback-row,.feedback-slider,.record-box,input,select,textarea,.btn-sec,.atbtn-reset,.atpreset,.pill){background:#2b2830!important;border-color:#4b4551!important;color:#f8f4f9!important}body.celeste-oled :is(.affirmation-display,.feedback-row,.feedback-slider,.record-box,input,select,textarea,.btn-sec,.atbtn-reset,.atpreset,.pill){background:#0d0d0d!important;border-color:#303030!important;color:#fafafa!important;box-shadow:none!important}
body.celeste-dark .timer-clock{background:conic-gradient(from -90deg,var(--pink) 0%,#c97fff var(--timer-progress),#413b47 var(--timer-progress),#413b47 100%)!important}body.celeste-oled .timer-clock{background:conic-gradient(from -90deg,var(--pink) 0%,#c97fff var(--timer-progress),#242424 var(--timer-progress),#242424 100%)!important;box-shadow:none!important}body.celeste-dark .timer-clock:before{background:#29262e!important}body.celeste-oled .timer-clock:before{background:#090909!important;box-shadow:none!important}
body.celeste-dark .streak-banner{background:linear-gradient(135deg,#311d2a,#25182f)!important;border-color:#59364e!important}body.celeste-oled .streak-banner{background:linear-gradient(135deg,#170a10,#110817)!important;border-color:#3b1e31!important}
body.celeste-dark .prog-wrap,body.celeste-oled .prog-wrap{background:#292929!important}body.celeste-dark input[type=range],body.celeste-oled input[type=range]{background:transparent!important;border:0!important}
body.celeste-dark :is(.section-title,.feedback-label,.streak-goal,.meta-total-row,.tts-toggle,.speed-row,label,h1,h2,h3,strong),body.celeste-oled :is(.section-title,.feedback-label,.streak-goal,.meta-total-row,.tts-toggle,.speed-row,label,h1,h2,h3,strong){color:var(--text)!important}body.celeste-dark :is(.affirm-timer-title,.streak-label,.stat-lbl,.hint,.feedback-hint,.feedback-status,.app-subtitle),body.celeste-oled :is(.affirm-timer-title,.streak-label,.stat-lbl,.hint,.feedback-hint,.feedback-status,.app-subtitle){color:var(--text-soft)!important}
body.celeste-dark #celeste-theme-control button,body.celeste-oled #celeste-theme-control button{background:#17151a;color:#eee8f0;border-color:#3b3740}body.celeste-oled #celeste-theme-control button{background:#0b0b0b;border-color:#292929}body.celeste-dark #celeste-theme-control button.active,body.celeste-oled #celeste-theme-control button.active{background:linear-gradient(135deg,#ff6e99,#b968ff)!important;color:#fff!important;border-color:transparent!important}body.celeste-dark option{background:#2b2830}body.celeste-oled option{background:#0d0d0d}body.celeste-dark input::placeholder,body.celeste-oled input::placeholder{color:#928b96!important}
`;doc.head.appendChild(s)}
function control(doc){if(doc.getElementById('celeste-theme-control'))return;const h=doc.querySelector('.app-header');if(!h)return;const b=doc.createElement('div');b.id='celeste-theme-control';b.innerHTML='<button data-theme="light">☀️ Claro</button><button data-theme="dark">🌙 Oscuro</button><button data-theme="oled">⚫ Ahorro OLED</button>';h.insertAdjacentElement('afterend',b);b.onclick=e=>{const x=e.target.closest('[data-theme]');if(x)setMode(x.dataset.theme)}}
function inner(doc,m){style(doc);control(doc);installedDoc=doc;doc.body.classList.toggle('celeste-dark',m==='dark');doc.body.classList.toggle('celeste-oled',m==='oled');doc.querySelectorAll('#celeste-theme-control button').forEach(b=>b.classList.toggle('active',b.dataset.theme===m))}function setMode(m){try{localStorage.setItem(KEY,m)}catch(_){}outer(m);if(frame.contentDocument)inner(frame.contentDocument,m)}function install(){const d=frame.contentDocument;if(d&&d.body)inner(d,getMode())}outer(getMode());frame.addEventListener('load',()=>setTimeout(install,150));let n=0,t=setInterval(()=>{install();if((installedDoc&&frame.contentDocument===installedDoc)||++n>80)clearInterval(t)},100)})();